require("lommix.plugins")
require("lommix.options")
require("lommix.keybinds")
require("lommix.lualine")
require("lommix.lualine-lsp")
require("lommix.auto")
require("lommix.lsp")
require("lommix.reloader")
require("lommix.lsp-inlayhints")
-- require'lommix.lspsage'
require("lommix.toggleterm")
require("lommix.autotag")
require("lommix.autopair")
require("lommix.treesitter")
require("lommix.globals")
require("lommix.telescope")
require("lommix.sniprun")
require("lommix.cmp")
require("lommix.scripts")
require("lommix.formatter")
require("lommix.godot")
require("lommix.harpoon")
require("lommix.comment")
require("lommix.highlight-colors")
require("lommix.indent-line")
require("lommix.codeium")
require("lommix.scripts.sftp")
require("lommix.chatgpt")
require("lommix.obsidian")
-- after plugins

vim.cmd[[colorscheme terafox]]
-- vim.cmd("colorscheme sobrio_ghost")
-- vim.cmd("syntax on")
--
-- after after
require("lommix.dap")
require("lommix.luasnip")
