hl.on("hyprland.start", function()
  hl.exec_cmd("~/.local/bin/watch_waybar.sh")
  hl.exec_cmd("hyprpaper")
  hl.exec_cmd("sleep 1 && dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
  hl.exec_cmd("hypridle")
  hl.exec_cmd("hyprpm reload")
  hl.exec_cmd("swaync")
  hl.exec_cmd("wl-paste --type text --watch cliphist store")
  hl.exec_cmd("wl-paste --type image --watch cliphist store")
  hl.exec_cmd("hyprctl setcursor Bibata-Modern-Classic 48")
end)