-- window rules (all commented out, kept for reference)

-- hl.window_rule({
--   name = "webcord-workspace",
--   match = { class = "^(WebCord)$" },
--   workspace = "3",
-- })
--
-- hl.window_rule({
--   name = "poe-immediate",
--   match = { class = "^(Path of Exile)$" },
--   workspace = "8",
--   immediate = true,
-- })
--
-- hl.window_rule({
--   name = "xwayland-video-bridge",
--   match = { class = "^(xwaylandvideobridge)$" },
--   opacity = 0.0,
--   no_anim = true,
--   no_initial_focus = true,
--   max_size = { 1, 1 },
--   no_blur = true,
-- })
--
-- hl.window_rule({
--   name = "float-dialogs",
--   match = { title = "^(Open File)(.*)$" },
--   float = true,
-- })
-- hl.window_rule({
--   name = "float-select-file",
--   match = { title = "^(Select a File)(.*)$" },
--   float = true,
-- })
-- hl.window_rule({
--   name = "float-choose-wallpaper",
--   match = { title = "^(Choose wallpaper)(.*)$" },
--   float = true,
-- })
-- hl.window_rule({
--   name = "float-open-folder",
--   match = { title = "^(Open Folder)(.*)$" },
--   float = true,
-- })
-- hl.window_rule({
--   name = "float-save-as",
--   match = { title = "^(Save As)(.*)$" },
--   float = true,
-- })
-- hl.window_rule({
--   name = "float-library",
--   match = { title = "^(Library)(.*)$" },
--   float = true,
-- })